services:
  - type: web
    name: mcp-server
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/mcpServer.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORTI_CLIENT_ID
        sync: false
      - key: CORTI_CLIENT_SECRET
        sync: false
      - key: CORTI_TENANT_NAME
        sync: false
      - key: CORTI_ENVIRONMENT
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
